#!/usr/bin/perl

# Corrects the file types for common extensions

use warnings;
use strict;

my $DIRCMD = "hdir";
my $ATTRIBCMD = "hattrib";
my $TEMPFILE = "/tmp/filenames";
my $VERSION = "1.0";

# Main Code		================================

print "fixsit ($VERSION)\n";
print "=====================\n";

# Get a list of the files in the volume
system("$DIRCMD > $TEMPFILE");

# Open the fie list
open(FH, '<', "$TEMPFILE") or die $!;

# Loop for all lines in the file
while(<FH>)
{
	#print $_;
	#my ($filedir, $filetype, $somefield, $filesize, $date, $day, $time, $filename) = split(/\s+/, $_);
	my ($filedir, $filetype) = split(/\s+/, $_);
	my $filename = substr($_, 46);
	chop($filename);
	#print "filename = $filename\n";
	if ($filedir ne "f")
	{
		print "Saw a directory for $filedir\n";
		next;
	}
	# print "Saw a file\n";
	# print "Type was $filetype\n";
	if ($filetype ne "????/UNIX")
	{
		#print "Filetype was $filetype\n";
		next;
	}
	# Get the file extension
	my $fileext = substr($filename, -3);
	print "Unconverted file extension is $fileext\n";
	if (($fileext eq "sit") || ($fileext eq "SIT"))
	{
		print "Saw a .sit file\n";
		system ("$ATTRIBCMD -t 'SIT5' -c 'SIT!' '$filename'");
	}
	if (($fileext eq "pdf") || ($fileext eq "PDF"))
	{
		print "Saw a .pdf file\n";
		system ("$ATTRIBCMD -t '????' -c 'PDF ' '$filename'");
	}
	if (($fileext eq "zip") || ($fileext eq "ZIP"))
	{
		print "Saw a .zip file\n";
		system ("$ATTRIBCMD -t 'ZIP ' -c 'SITx' '$filename'");
	}

}
close(FH);

exit 0;
